# Generated by Django 5.1.4 on 2024-12-21 00:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('fecha_nac', models.DateField()),
                ('dni', models.CharField(max_length=20, unique=True)),
                ('direccion', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField()),
                ('direccion', models.CharField()),
                ('ciudad', models.CharField()),
                ('telefono', models.CharField()),
                ('cant_aulas', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('año_dictado', models.IntegerField()),
                ('duracion', models.IntegerField()),
                ('tema', models.CharField()),
                ('costo_mensual', models.DecimalField(decimal_places=3, max_digits=20)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('alumnos', models.ManyToManyField(to='gestionCursos.alumno')),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionCursos.sede')),
            ],
        ),
    ]
