# Generated by Django 6.0 on 2025-12-12 13:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('fecha_nac', models.DateField()),
                ('dni', models.CharField(max_length=8, unique=True, validators=[django.core.validators.MinLengthValidator(8)])),
                ('direccion', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField()),
                ('direccion', models.CharField()),
                ('ciudad', models.CharField()),
                ('telefono', models.CharField()),
                ('cant_aulas', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('codigo_curso', models.IntegerField(primary_key=True, serialize=False)),
                ('año_dictado', models.IntegerField()),
                ('duracion', models.IntegerField()),
                ('tema', models.CharField()),
                ('costo_mensual', models.DecimalField(decimal_places=3, max_digits=20)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('alumnos', models.ManyToManyField(to='gestionCursos.alumno')),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionCursos.sede')),
            ],
        ),
        migrations.CreateModel(
            name='Inscripcion_Curso_Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionCursos.alumno')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionCursos.curso')),
            ],
        ),
    ]
