# Generated by Django 5.1.4 on 2024-12-21 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionCursos', '0002_remove_curso_id_curso_codigo_curso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='codigo_curso',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
