# Generated by Django 5.1.4 on 2024-12-22 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionCursos', '0005_inscripcion_curso_alumno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscripcion_curso_alumno',
            name='nota',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
